### ISSUE TITLE
What does the error "SymbolicJump" mean?

### ISSUE THREAD

**Issue by friday-james** [leonardoalt/dl_symb_exec_sol#1]
Got an error while applying this tool to a rather complicated contract.
The error is:
```
Failed tests:
[FAIL. Reason: SymbolicJump()] test_symb() (gas: 23439276795)
```
What does that mean?

**Comment by leonardoalt** [comment]
> Got an error while applying this tool to a rather complicated contract.

lmao why on earth would you do that

This error means that there was a JUMP or JUMPI that did not have a concrete value on top of the stack. Likely causes are back jumps from internal/helper functions and function pointers.
